//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.9

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sensor_data")]
pub struct Model {
    pub container_id: String,
    pub data: Option<Json>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::data_container::Entity",
        from = "Column::ContainerId",
        to = "super::data_container::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DataContainer,
}

impl Related<super::data_container::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataContainer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
